title: Guía de Estrategia web
logo: /assets/img/logo.png
description: Guía de Estrategia web de la Dirección de Información y Tecnologías DSIT de la Universidad de Los Andes. Versión 1.0.0.
show_downloads: false
theme: jekyll-theme-minimal
